include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Estilo/legibilidade
    always_declare_return_types: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    use_key_in_widget_constructors: true
    directives_ordering: true
    cascade_invocations: true

    # Segurança/boas práticas
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_relative_lib_imports: true
    unawaited_futures: true

    # Null-safety/erros comuns
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_late: true

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    # Trate avisos importantes como erro para manter padrão alto
    unused_import: error
    dead_code: error
    missing_return: error
    prefer_const_constructors: warning
    prefer_const_literals_to_create_immutables: warning
