name: brasil_cripto
description: "Aplicativo para acompanhamento de criptomoedas"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  shared_preferences: ^2.2.3
  fl_chart: ^0.68.0
  intl: ^0.19.0
  google_fonts: ^6.2.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  mocktail: ^1.0.3

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/branding/logo.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/branding/logo.png
  remove_alpha_ios: true

flutter:

  uses-material-design: true
  assets:
    - assets/branding/logo.png
